version: "3"

services:
  api:
    container_name: flask_api
    build: .
    links:
     - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/myapp
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro